/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-10-19 05:36:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Entity.User;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/H:/SOF203/Assignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Assignment/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1759452326271L));
    _jspx_dependants.put("jar:file:/H:/SOF203/Assignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Assignment/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/includes/news_index_left.jsp", Long.valueOf(1760852157685L));
    _jspx_dependants.put("/includes/news_index_center.jsp", Long.valueOf(1760852157673L));
    _jspx_dependants.put("/includes/news_index_footer.jsp", Long.valueOf(1760852157709L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Entity.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    String fullname = (user != null && user.getFullname() != null)
        ? user.getFullname() : "Quản trị viên";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>ABC News - Trang Quản Trị</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .popup-overlay {\r\n");
      out.write("            position: fixed; inset: 0;\r\n");
      out.write("            background: rgba(0,0,0,0.6);\r\n");
      out.write("            display: none; justify-content: center; align-items: center;\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("        }\r\n");
      out.write("        .popup-form {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            width: 380px; padding: 35px 25px 25px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(0,0,0,0.3);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            animation: fadeIn 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .popup-form h3 { color: #0d47a1; margin-bottom: 8px; }\r\n");
      out.write("        .popup-form p { font-size: 14px; color: #555; margin-bottom: 20px; }\r\n");
      out.write("        .popup-form input {\r\n");
      out.write("            width: 100%; padding: 10px; margin-bottom: 15px;\r\n");
      out.write("            border: 1px solid #ccc; border-radius: 8px; font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .popup-form button[type=\"submit\"] {\r\n");
      out.write("            width: 100%; padding: 10px 25px;\r\n");
      out.write("            background: #ffcc00; border: none; border-radius: 8px;\r\n");
      out.write("            font-weight: bold; cursor: pointer; transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .popup-form button:hover { background: #fdd835; }\r\n");
      out.write("        .close-icon {\r\n");
      out.write("            position: absolute; top: 10px; right: 12px;\r\n");
      out.write("            background: none; border: none;\r\n");
      out.write("            font-size: 22px; font-weight: bold; color: #555;\r\n");
      out.write("            cursor: pointer; transition: color 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .close-icon:hover { color: #e53935; }\r\n");
      out.write("        @keyframes fadeIn { from {opacity: 0; transform: scale(0.9);} to {opacity: 1; transform: scale(1);} }\r\n");
      out.write("\r\n");
      out.write("        .change-pass-btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background: #ffcc00; color: #000;\r\n");
      out.write("            padding: 10px 18px; border-radius: 8px;\r\n");
      out.write("            font-weight: bold; text-align: center;\r\n");
      out.write("            margin-bottom: 20px; transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .change-pass-btn:hover { background: #fdd835; }\r\n");
      out.write("\r\n");
      out.write("        .admin-banner h2 { margin-bottom: 20px; color: #0d47a1; }\r\n");
      out.write("        .admin-stats {\r\n");
      out.write("            display: flex; gap: 15px; margin-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-box {\r\n");
      out.write("            flex: 1; background: #fff; border-radius: 10px;\r\n");
      out.write("            padding: 15px; text-align: center;\r\n");
      out.write("            box-shadow: 0 2px 6px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .stat-box h4 { margin: 5px 0; color: #0d47a1; }\r\n");
      out.write("        .admin-actions { display: flex; flex-direction: column; gap: 10px; }\r\n");
      out.write("        .admin-btn {\r\n");
      out.write("            display: block; padding: 10px;\r\n");
      out.write("            background: #0d47a1; color: #fff; border-radius: 8px;\r\n");
      out.write("            text-align: center; transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .admin-btn:hover { background: #1565c0; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("    <header class=\"site-header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"logo\">ABC <span>News</span></div>\r\n");
      out.write("          <nav class=\"menu\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\"\r\n");
      out.write("       class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, '/index') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Trang chủ</a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?name=Văn hóa\"\r\n");
      out.write("   class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, 'Văn hóa') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Văn hóa</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?name=Pháp luật\"\r\n");
      out.write("   class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, 'Pháp luật') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Pháp luật</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?name=Thể thao\"\r\n");
      out.write("   class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, 'Thể thao') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Thể thao</a>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin\"\r\n");
      out.write("       class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, '/admin') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Quản trị</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-actions\">\r\n");
      out.write("	<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\" method=\"get\" class=\"search-form\">\r\n");
      out.write("				    <input type=\"text\" name=\"keyword\" placeholder=\"Tìm kiếm tin tức...\" class=\"search-bar\" required>\r\n");
      out.write("				    <button type=\"submit\" class=\"search-btn\">🔍</button>\r\n");
      out.write("				</form>\r\n");
      out.write("    Xin chào <strong>");
      out.print( user.getFullname() != null ? user.getFullname() : "Admin" );
      out.write("</strong>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout-btn\">Đăng xuất</a>\r\n");
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- MAIN -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"container-3col\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Cột trái -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"left-col\">\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Cột giữa -->\r\n");
      out.write("            <section class=\"center-col\">     \r\n");
      out.write("               <h2>Quản trị hệ thống</h2>\r\n");
      out.write("                <div class=\"admin-actions\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage_users\"\r\n");
      out.write("   style=\"display:inline-block; \r\n");
      out.write("          margin:8px 10px; \r\n");
      out.write("          padding:10px 18px; \r\n");
      out.write("          background:linear-gradient(135deg, #007bff, #0056b3); \r\n");
      out.write("          color:white; \r\n");
      out.write("          font-weight:600; \r\n");
      out.write("          border-radius:8px; \r\n");
      out.write("          text-decoration:none; \r\n");
      out.write("          transition:all 0.25s ease;\r\n");
      out.write("          box-shadow:0 2px 5px rgba(0,0,0,0.15);\"\r\n");
      out.write("   onmouseover=\"this.style.background='linear-gradient(135deg,#0056b3,#003d80)'\"\r\n");
      out.write("   onmouseout=\"this.style.background='linear-gradient(135deg,#007bff,#0056b3)'\">\r\n");
      out.write("   Quản lý người dùng\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage_categories\"\r\n");
      out.write("   style=\"display:inline-block; \r\n");
      out.write("          margin:8px 10px; \r\n");
      out.write("          padding:10px 18px; \r\n");
      out.write("          background:linear-gradient(135deg, #28a745, #1e7e34); \r\n");
      out.write("          color:white; \r\n");
      out.write("          font-weight:600; \r\n");
      out.write("          border-radius:8px; \r\n");
      out.write("          text-decoration:none; \r\n");
      out.write("          transition:all 0.25s ease;\r\n");
      out.write("          box-shadow:0 2px 5px rgba(0,0,0,0.15);\"\r\n");
      out.write("   onmouseover=\"this.style.background='linear-gradient(135deg,#1e7e34,#155d27)'\"\r\n");
      out.write("   onmouseout=\"this.style.background='linear-gradient(135deg,#28a745,#1e7e34)'\">\r\n");
      out.write("   Quản lý loại tin\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage_all_news\"\r\n");
      out.write("   style=\"display:inline-block; \r\n");
      out.write("          margin:8px 10px; \r\n");
      out.write("          padding:10px 18px; \r\n");
      out.write("          background:linear-gradient(135deg, #ffc107, #e0a800); \r\n");
      out.write("          color:#333; \r\n");
      out.write("          font-weight:600; \r\n");
      out.write("          border-radius:8px; \r\n");
      out.write("          text-decoration:none; \r\n");
      out.write("          transition:all 0.25s ease;\r\n");
      out.write("          box-shadow:0 2px 5px rgba(0,0,0,0.15);\"\r\n");
      out.write("   onmouseover=\"this.style.background='linear-gradient(135deg,#e0a800,#c69500)'\"\r\n");
      out.write("   onmouseout=\"this.style.background='linear-gradient(135deg,#ffc107,#e0a800)'\">\r\n");
      out.write("   Quản lý bài viết\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </section>\r\n");
      out.write("			\r\n");
      out.write("            <aside class=\"right-col\">\r\n");
      out.write("                <a href=\"#\" class=\"change-pass-btn\" onclick=\"openPopup()\">Đổi mật khẩu</a>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <h3>Thông tin hệ thống</h3>\r\n");
      out.write("                    <p><strong>Cập nhật lần cuối:</strong> 28/09/2025 16:42</p>\r\n");
      out.write("                    <p><strong>Phiên bản:</strong> 1.0.0</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <h3>Tin tức hấp dẫn</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("           <section class=\"center-col\">\r\n");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"popup-overlay\" id=\"popupOverlay\">\r\n");
      out.write("        <div class=\"popup-form\">\r\n");
      out.write("            <button type=\"button\" class=\"close-icon\" onclick=\"closePopup()\">×</button>\r\n");
      out.write("            <h3>Đổi mật khẩu</h3>\r\n");
      out.write("            <p>Vui lòng nhập thông tin để thay đổi mật khẩu của bạn</p>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/changePassword\" method=\"post\">\r\n");
      out.write("                <input type=\"password\" name=\"oldPassword\" placeholder=\"Mật khẩu cũ\" required>\r\n");
      out.write("                <input type=\"password\" name=\"newPassword\" placeholder=\"Mật khẩu mới\" required>\r\n");
      out.write("                <input type=\"password\" name=\"confirmPassword\" placeholder=\"Xác nhận mật khẩu mới\" required>\r\n");
      out.write("                <button type=\"submit\">Xác nhận</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <footer class=\"site-footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <p>&copy; 2025 ABC News. All rights reserved.</p>\r\n");
      out.write("            <div class=\"social-links\">\r\n");
      out.write("                <a href=\"#\">Facebook</a> | <a href=\"#\">Twitter</a> | <a href=\"#\">Instagram</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>Liên hệ: contact@abcnews.vn | Hotline: 0123 456 789</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function openPopup() {\r\n");
      out.write("            document.getElementById('popupOverlay').style.display = 'flex';\r\n");
      out.write("        }\r\n");
      out.write("        function closePopup() {\r\n");
      out.write("            document.getElementById('popupOverlay').style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /includes/news_index_left.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("n");
    // /includes/news_index_left.jsp(6,0) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/includes/news_index_left.jsp(6,0) '${homeLeft}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${homeLeft}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <article class=\"news-item\">\r\n");
          out.write("            <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/uploads/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.image}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("            <div class=\"news-content\">\r\n");
          out.write("                <h3><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/detail?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></h3>\r\n");
          out.write("                \r\n");
          out.write("                <span class=\"news-meta\">Đăng ngày: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.postedDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("            </div>\r\n");
          out.write("        </article>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /includes/news_index_center.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("n");
    // /includes/news_index_center.jsp(3,0) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/includes/news_index_center.jsp(3,0) '${homeCenter}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${homeCenter}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <article class=\"news-item\">\r\n");
          out.write("            <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/uploads/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.image}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("            <div class=\"news-content\">\r\n");
          out.write("                <h3><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/detail?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></h3>\r\n");
          out.write("                <span class=\"news-meta\">Đăng ngày: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.postedDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("            </div>\r\n");
          out.write("        </article>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    return false;
  }
}
