/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-10-26 23:13:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Entity.User;

public final class manage_005fcategories_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/H:/SOF203/Assignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Assignment/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1759452326271L));
    _jspx_dependants.put("jar:file:/H:/SOF203/Assignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Assignment/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/includes/news_index_footer.jsp", Long.valueOf(1760852157709L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Entity.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    String fullname = (user != null && user.getFullname() != null)
            ? user.getFullname() : "Quản trị viên";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"ABC News - Quản lý loại tin\">\r\n");
      out.write("    <title>ABC News - Quản lý loại tin</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("/* ================================================= */\r\n");
      out.write("/* CƠ SỞ CHUNG (Đồng bộ với các trang Admin khác) */\r\n");
      out.write("/* ================================================= */\r\n");
      out.write("body {\r\n");
      out.write("    background-color: #eef1f5; /* Nền xám nhạt hiện đại */\r\n");
      out.write("    color: #495057; /* Màu chữ chính */\r\n");
      out.write("    font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* HEADER & MENU (Giả định đã có CSS chung) */\r\n");
      out.write(".site-header { background-color: #1a2a47; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); }\r\n");
      out.write(".logo { color: #ffffff; font-weight: 700; }\r\n");
      out.write(".logo span { color: #fcc419; }\r\n");
      out.write(".logout-btn { background: #e53935; color: white; }\r\n");
      out.write("\r\n");
      out.write("/* CỘT NỘI DUNG CHÍNH */\r\n");
      out.write(".center-col {\r\n");
      out.write("    background: #ffffff;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".center-col h2 {\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    color: #1a2a47; /* Xanh Navy Sâu */\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    border-bottom: 3px solid #fcc419; /* Vàng ấm nổi bật */\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================================================= */\r\n");
      out.write("/* THANH HÀNH ĐỘNG & NÚT THÊM (Đồng bộ với Quản lý tin tức) */\r\n");
      out.write("/* ================================================= */\r\n");
      out.write(".action-bar { margin-bottom: 20px; }\r\n");
      out.write(".action-bar .add-news-btn { /* Đổi tên class để phù hợp hơn, nhưng vẫn dùng style này */\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    background: #1a2a47; /* Xanh Navy Sâu */\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    transition: background 0.3s, transform 0.3s;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write(".action-bar .add-news-btn:hover {\r\n");
      out.write("    background: #273e63;\r\n");
      out.write("    transform: translateY(-1px);\r\n");
      out.write("    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================================================= */\r\n");
      out.write("/* BẢNG (TABLE) */\r\n");
      out.write("/* ================================================= */\r\n");
      out.write(".news-table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: separate;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".news-table thead th {\r\n");
      out.write("    background: #1a2a47; /* Xanh Navy Sâu */\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("    padding: 15px 10px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".news-table tbody tr { border-bottom: 1px solid #e9ecef; }\r\n");
      out.write(".news-table tbody tr:hover { background: #f1f4f8; }\r\n");
      out.write(".news-table td { padding: 12px 10px; vertical-align: middle; color: #495057; }\r\n");
      out.write("\r\n");
      out.write("/* NÚT HÀNH ĐỘNG TRONG BẢNG */\r\n");
      out.write(".edit-btn, .delete-btn {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 6px 12px;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("    transition: all 0.2s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sửa: Xanh dương tiêu chuẩn */\r\n");
      out.write(".edit-btn {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("}\r\n");
      out.write(".edit-btn:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Xóa: Đỏ dịu */\r\n");
      out.write(".delete-btn {\r\n");
      out.write("    background-color: #e53935;\r\n");
      out.write("}\r\n");
      out.write(".delete-btn:hover {\r\n");
      out.write("    background-color: #c62828;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================================================= */\r\n");
      out.write("/* MODAL (Popup) */\r\n");
      out.write("/* ================================================= */\r\n");
      out.write(".modal {\r\n");
      out.write("    display: none; /* Ẩn mặc định */\r\n");
      out.write("    position: fixed; inset: 0;\r\n");
      out.write("    background: rgba(26, 42, 71, 0.8); /* Xanh Navy mờ */\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    z-index: 10000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content {\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    box-shadow: 0 10px 40px rgba(0,0,0,0.3);\r\n");
      out.write("    position: relative;\r\n");
      out.write("    animation: fadeIn 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content h2 {\r\n");
      out.write("    color: #1a2a47;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    border-bottom: 1px solid #e9ecef;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close-btn {\r\n");
      out.write("    position: absolute; top: 10px; right: 15px;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #adb5bd;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("    transition: color 0.2s;\r\n");
      out.write("}\r\n");
      out.write(".close-btn:hover { color: #dc3545; }\r\n");
      out.write("\r\n");
      out.write("/* Form */\r\n");
      out.write(".form-group { margin-bottom: 15px; }\r\n");
      out.write(".form-group label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    color: #495057;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".form-group input[type=\"text\"] {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px 12px;\r\n");
      out.write("    border: 1px solid #ced4da;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    transition: border-color 0.2s;\r\n");
      out.write("}\r\n");
      out.write(".form-group input[type=\"text\"]:focus {\r\n");
      out.write("    border-color: #fcc419; /* Vàng ấm khi focus */\r\n");
      out.write("    outline: none;\r\n");
      out.write("    box-shadow: 0 0 0 0.2rem rgba(252, 196, 25, 0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nút Submit */\r\n");
      out.write(".submit-btn {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    background: #fcc419; /* Vàng ấm */\r\n");
      out.write("    color: #1a2a47; /* Chữ Xanh Navy */\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background 0.3s;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(252, 196, 25, 0.3);\r\n");
      out.write("}\r\n");
      out.write(".submit-btn:hover {\r\n");
      out.write("    background: #ffbe00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fadeIn {\r\n");
      out.write("    from { opacity: 0; transform: scale(0.95); }\r\n");
      out.write("    to { opacity: 1; transform: scale(1); }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"logo\">ABC <span>News</span></div>\r\n");
      out.write("<nav class=\"menu\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\"\r\n");
      out.write("       class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, '/index') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Trang chủ</a>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin\"\r\n");
      out.write("       class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, '/admin') ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">Quản trị</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-actions\">\r\n");
      out.write("            Xin chào <strong>");
      out.print( fullname );
      out.write("</strong>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout-btn\">Đăng xuất</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <section class=\"center-col\">\r\n");
      out.write("        <h2>Quản lý loại tin</h2>\r\n");
      out.write("        <div class=\"action-bar\">\r\n");
      out.write("            <a href=\"#\" class=\"add-news-btn\" onclick=\"showModal('add-category-modal')\">+ Thêm loại tin</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <table class=\"news-table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Mã loại tin</th>\r\n");
      out.write("                <th>Tên loại tin</th>\r\n");
      out.write("                <th>Hành động</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal thêm loại tin -->\r\n");
      out.write("<div id=\"add-category-modal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close-btn\" onclick=\"closeModal('add-category-modal')\">&times;</span>\r\n");
      out.write("        <h2>Thêm loại tin</h2>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/add_category\" method=\"post\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"categoryName\">Tên loại tin</label>\r\n");
      out.write("                <input type=\"text\" id=\"categoryName\" name=\"categoryName\" placeholder=\"Nhập tên loại tin\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">Thêm</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal sửa loại tin -->\r\n");
      out.write("<div id=\"edit-category-modal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close-btn\" onclick=\"closeModal('edit-category-modal')\">&times;</span>\r\n");
      out.write("        <h2>Sửa loại tin</h2>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/edit_category\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" id=\"edit-id\" name=\"categoryId\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"edit-name\">Tên loại tin</label>\r\n");
      out.write("                <input type=\"text\" id=\"edit-name\" name=\"categoryName\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">Lưu thay đổi</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <footer class=\"site-footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <p>&copy; 2025 ABC News. All rights reserved.</p>\r\n");
      out.write("            <div class=\"social-links\">\r\n");
      out.write("                <a href=\"#\">Facebook</a> | <a href=\"#\">Twitter</a> | <a href=\"#\">Instagram</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>Liên hệ: contact@abcnews.vn | Hotline: 0123 456 789</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function showModal(id) {\r\n");
      out.write("        document.getElementById(id).style.display = 'flex';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeModal(id) {\r\n");
      out.write("        document.getElementById(id).style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openEditModal(id, name) {\r\n");
      out.write("        document.getElementById('edit-id').value = id;\r\n");
      out.write("        document.getElementById('edit-name').value = name;\r\n");
      out.write("        showModal('edit-category-modal');\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /admin/manage_categories.jsp(229,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("c");
    // /admin/manage_categories.jsp(229,4) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/manage_categories.jsp(229,4) '${categories}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/category?name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("           class=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(pageContext.request.requestURI, c.name) ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("\">\r\n");
          out.write("            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("        </a>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /admin/manage_categories.jsp(265,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("c");
    // /admin/manage_categories.jsp(265,12) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/admin/manage_categories.jsp(265,12) '${categories}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <tr>\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                    <td>\r\n");
          out.write("                        <a href=\"#\" class=\"edit-btn\"\r\n");
          out.write("                           onclick=\"openEditModal('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">Sửa</a>\r\n");
          out.write("                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/delete_category?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                           class=\"delete-btn\"\r\n");
          out.write("                           onclick=\"return confirm('Bạn có chắc muốn xóa loại tin này?')\">Xóa</a>\r\n");
          out.write("                    </td>\r\n");
          out.write("                </tr>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    return false;
  }
}
